name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: cd container && docker build . --file Containerfile --tag roku-dev-container:$(date +%s) --tag roku-dev-container:latest --build-arg NODE_VERSION=16.15.1
    - name: Export image to file
      run: docker save roku-dev-container:latest | zstd -19 -o rokudev.tar.zstd
    - uses: actions/upload-artifact@v3
      with:
        name: rokudev
        path: rokudev.tar.zstd
